// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © uselessakk30

//@version=6
indicator(title="RSI and Stochastic Indicator", format=format.price, overlay = true, max_labels_count = 200)

//RSI
len = input.int(title="RSI Period", minval=1, defval=14)
src = input(title="RSI Source", defval=close)
osc = ta.rsi(src, len) 

//RSI MAIN LINE
plot(osc, title="RSI", linewidth=2, color=color.rgb(141, 24, 150))


_evunder = ta.crossunder(source1 = osc, source2 = 50) 
_evuover = ta.crossover(source1 = osc, source2 = 50) 
//RSI CIRCLE

if _evunder
    label.new(bar_index, osc, yloc=yloc.price, color=color.rgb(255, 0, 0), style=label.style_circle, size=2)
if _evuover
    label.new(bar_index, osc, yloc=yloc.price, color=color.rgb(60, 255, 0), style=label.style_circle, size=2)

//RSI LINES
//hline(50, title="Middle Line", color=#787B86, linestyle=hline.style_dotted)
obLevel = hline(70, title="Overbought", color=#787B86, linestyle=hline.style_dotted)
osLevel = hline(30, title="Oversold", color=#787B86, linestyle=hline.style_dotted)
fill(obLevel, osLevel, title="Background", color=color.rgb(141, 24, 150, 90))


//STOCHASTIC
periodK = input.int(14, title="%K Length", minval=1)
smoothK = input.int(1, title="%K Smoothing", minval=1)
periodD = input.int(3, title="%D Smoothing", minval=1)
k = ta.sma(ta.stoch(close, high, low, periodK), smoothK)
d = ta.sma(k, periodD)

//STOCHASTIC MAIN LINE
//plot(k, title="%K", color=#2962FF)
plot(d, title="%D", color=#FF6D00)

//STOCHASTIC LINES
hline(50, "Middle Band", color=color.new(#fdfdfd, 50))
h0 = hline(80, "Upper Band", color=color.new(#fdfdfd, 50))
h1 = hline(20, "Lower Band", color=color.new(#fdfdfd, 50))
//fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")
